name: vmh_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  data_table_2: ^2.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.0
  http: ^1.4.0
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Goldman
      fonts:
        - asset: assets/fonts/Goldman.ttf
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap/Asap-Regular.ttf
        - asset: assets/fonts/Asap/Asap-Black.ttf
          weight: 900
        - asset: assets/fonts/Asap/Asap-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Asap/Asap-Bold.ttf
          weight: 700
        - asset: assets/fonts/Asap/Asap-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Asap/Asap-Medium.ttf
          weight: 500
        - asset: assets/fonts/Asap/Asap-Regular.ttf
          weight: 400
        - asset: assets/fonts/Asap/Asap-Light.ttf
          weight: 300
        - asset: assets/fonts/Asap/Asap-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Asap/Asap-Thin.ttf
          weight: 100
        # Asap-Italic / font nghiêng
        - asset: assets/fonts/Asap/Asap-Italic.ttf
          style: italic
        - asset: assets/fonts/Asap/Asap-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Asap/Asap-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Asap/Asap-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Asap/Asap-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Asap/Asap-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Asap/Asap-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Asap/Asap-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Asap/Asap-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Asap/Asap-ThinItalic.ttf
          weight: 100
          style: italic

